In [1]:
import pandas as pd

from fast_ml.utilities import display_all
from fast_ml.feature_selection import get_constant_features

In [2]:
df = pd.read_csv("dataset_1.csv")
df.head()

,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,...,var_292,var_293,var_294,var_295,var_296,var_297,var_298,var_299,var_300,target
0,0,0,0.0,0.00,0.0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0.0,0.0000,0
1,0,0,0.0,3.00,0.0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0.0,0.0000,0
2,0,0,0.0,5.88,0.0,0,0,0,0,0,...,0.0,0,0,3,0,0,0,0.0,67772.7216,0
3,0,0,0.0,14.10,0.0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0.0,0.0000,0
4,0,0,0.0,5.76,0.0,0,0,0,0,0,...,0.0,0,0,0,0,0,0,0.0,0.0000,0

In [3]:
#what this will do is get a constant features, we are also setting a threshold to drop values that are 99% constant
constant_features = get_constant_features(df, threshold = 0.99, dropna = False)

#the output is a dataframe with description, name of the variable, value, and how 
constant_features.head()

       Desc      Var Value   Perc
0  Constant   var_80     0  100.0
1  Constant   var_97     0  100.0
2  Constant  var_113     0  100.0
3  Constant  var_112     0  100.0
4  Constant   var_33     0  100.0

In [4]:
constant_features_list = constant_features.query("Desc== 'Constant' ")['Var'].to_list()
print(constant_features_list)

['var_80', 'var_97', 'var_113', 'var_112', 'var_33', 'var_212', 'var_99', 'var_215', 'var_248', 'var_44', 'var_122', 'var_92', 'var_89', 'var_87', 'var_81', 'var_167', 'var_61', 'var_225', 'var_227', 'var_120', 'var_23', 'var_127', 'var_196', 'var_297', 'var_195', 'var_294', 'var_135', 'var_201', 'var_182', 'var_180', 'var_178', 'var_158', 'var_171']

In [5]:
#the quasiconstant features are also in the constant feautures dataframe so now we want to query for it
quasi_constant_list = constant_features.query("Desc == 'Quasi Constant' ")['Var'].to_list()
print(quasi_constant_list)

['var_124', 'var_223', 'var_73', 'var_183', 'var_133', 'var_129', 'var_104', 'var_69', 'var_170', 'var_67', 'var_280', 'var_66', 'var_287', 'var_14', 'var_34', 'var_36', 'var_247', 'var_283', 'var_10', 'var_12', 'var_151', 'var_285', 'var_6', 'var_217', 'var_72', 'var_65', 'var_11', 'var_141', 'var_153', 'var_210', 'var_187', 'var_189', 'var_228', 'var_111', 'var_233', 'var_234', 'var_243', 'var_150', 'var_2', 'var_9', 'var_265', 'var_28', 'var_20', 'var_267', 'var_71', 'var_116', 'var_289', 'var_7', 'var_146', 'var_263', 'var_221', 'var_257', 'var_90', 'var_59', 'var_204', 'var_274', 'var_126', 'var_136', 'var_239', 'var_149', 'var_138', 'var_202', 'var_216', 'var_235', 'var_264', 'var_1', 'var_60', 'var_3', 'var_184', 'var_95', 'var_42', 'var_290', 'var_237', 'var_142', 'var_260', 'var_78', 'var_45', 'var_53', 'var_299', 'var_77', 'var_254', 'var_219', 'var_43', 'var_106', 'var_211', 'var_197', 'var_246', 'var_224', 'var_102', 'var_24', 'var_48', 'var_32', 'var_115', 'var_125', 'var_159', 'var_98', 'var_282', 'var_286', 'var_39', 'var_298', 'var_245', 'var_249', 'var_40', 'var_236', 'var_130', 'var_16', 'var_56', 'var_251', 'var_291', 'var_293', 'var_238', 'var_193', 'var_194', 'var_128', 'var_119', 'var_199', 'var_278', 'var_177', 'var_84', 'var_250', 'var_94', 'var_198', 'var_13', 'var_273', 'var_137', 'var_22', 'var_242', 'var_139', 'var_256', 'var_218', 'var_240', 'var_26', 'var_156', 'var_5', 'var_25', 'var_134', 'var_63', 'var_268', 'var_27', 'var_213', 'var_165', 'var_68', 'var_154', 'var_19', 'var_172']

In [6]:
df.drop(columns = constant_features_list, inplace = True)
df

,var_1,var_2,var_3,var_4,var_5,var_6,var_7,var_8,var_9,var_10,...,var_290,var_291,var_292,var_293,var_295,var_296,var_298,var_299,var_300,target
0,0,0,0.0,0.00,0.0,0,0,0,0,0,...,0.0,0,0.00,0,0,0,0,0.0,0.0000,0
1,0,0,0.0,3.00,0.0,0,0,0,0,0,...,0.0,0,0.00,0,0,0,0,0.0,0.0000,0
2,0,0,0.0,5.88,0.0,0,0,0,0,0,...,0.0,0,0.00,0,3,0,0,0.0,67772.7216,0
3,0,0,0.0,14.10,0.0,0,0,0,0,0,...,0.0,0,0.00,0,0,0,0,0.0,0.0000,0
4,0,0,0.0,5.76,0.0,0,0,0,0,0,...,0.0,0,0.00,0,0,0,0,0.0,0.0000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,0,0,0.0,2.85,0.0,0,0,0,0,0,...,0.0,0,0.00,0,0,0,0,0.0,0.0000,0
49996,0,0,0.0,2.91,0.0,0,0,0,0,0,...,0.0,0,0.00,0,0,0,0,0.0,0.0000,0
49997,0,0,0.0,8.46,0.0,0,0,0,0,0,...,0.0,0,0.00,0,0,0,0,0.0,0.0000,0
49998,0,0,0.0,2.76,0.0,0,0,0,0,0,...,0.0,0,0.00,0,0,0,0,0.0,0.0000,0
49999,0,0,0.0,5.64,0.0,0,0,0,0,0,...,0.0,0,2.85,0,0,0,0,0.0,0.0000,0

In [9]:
df.drop(columns = quasi_constant_list, inplace = True)
df

KeyError: "['var_124' 'var_223' 'var_73' 'var_183' 'var_133' 'var_129' 'var_104'\n 'var_69' 'var_170' 'var_67' 'var_280' 'var_66' 'var_287' 'var_14'\n 'var_34' 'var_36' 'var_247' 'var_283' 'var_10' 'var_12' 'var_151'\n 'var_285' 'var_6' 'var_217' 'var_72' 'var_65' 'var_11' 'var_141'\n 'var_153' 'var_210' 'var_187' 'var_189' 'var_228' 'var_111' 'var_233'\n 'var_234' 'var_243' 'var_150' 'var_2' 'var_9' 'var_265' 'var_28' 'var_20'\n 'var_267' 'var_71' 'var_116' 'var_289' 'var_7' 'var_146' 'var_263'\n 'var_221' 'var_257' 'var_90' 'var_59' 'var_204' 'var_274' 'var_126'\n 'var_136' 'var_239' 'var_149' 'var_138' 'var_202' 'var_216' 'var_235'\n 'var_264' 'var_1' 'var_60' 'var_3' 'var_184' 'var_95' 'var_42' 'var_290'\n 'var_237' 'var_142' 'var_260' 'var_78' 'var_45' 'var_53' 'var_299'\n 'var_77' 'var_254' 'var_219' 'var_43' 'var_106' 'var_211' 'var_197'\n 'var_246' 'var_224' 'var_102' 'var_24' 'var_48' 'var_32' 'var_115'\n 'var_125' 'var_159' 'var_98' 'var_282' 'var_286' 'var_39' 'var_298'\n 'var_245' 'var_249' 'var_40' 'var_236' 'var_130' 'var_16' 'var_56'\n 'var_251' 'var_291' 'var_293' 'var_238' 'var_193' 'var_194' 'var_128'\n 'var_119' 'var_199' 'var_278' 'var_177' 'var_84' 'var_250' 'var_94'\n 'var_198' 'var_13' 'var_273' 'var_137' 'var_22' 'var_242' 'var_139'\n 'var_256' 'var_218' 'var_240' 'var_26' 'var_156' 'var_5' 'var_25'\n 'var_134' 'var_63' 'var_268' 'var_27' 'var_213' 'var_165' 'var_68'\n 'var_154' 'var_19' 'var_172'] not found in axis"

In [ ]:
https://www.kaggle.com/nextbigwhat/dataset-1